#############################################################################
# Makefile for building: Solution
# Generated by qmake (2.01a) (Qt 4.8.2) on: Sat Nov 22 15:16:25 2014
# Project:  Solution.pro
# Template: subdirs
# Command: /usr/bin/qmake-qt4 -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Solution.pro
#############################################################################

first: make_default
MAKEFILE      = Makefile
QMAKE         = /usr/bin/qmake-qt4
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = $(COPY_DIR)
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
SUBTARGETS    =  \
		sub-Common \
		sub-Atem \
		sub-Caspar \
		sub-TriCaster \
		sub-Panasonic \
		sub-Web \
		sub-Gpi \
		sub-Osc \
		sub-Repository \
		sub-Core \
		sub-Widgets \
		sub-Shell

Common//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Common/ || $(MKDIR) Common/ 
	cd Common/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Common/Common.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Common-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Common/ || $(MKDIR) Common/ 
	cd Common/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Common/Common.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Common: Common//$(MAKEFILE) FORCE
	cd Common/ && $(MAKE) -f $(MAKEFILE)
sub-Common-make_default: Common//$(MAKEFILE) FORCE
	cd Common/ && $(MAKE) -f $(MAKEFILE) 
sub-Common-make_first: Common//$(MAKEFILE) FORCE
	cd Common/ && $(MAKE) -f $(MAKEFILE) first
sub-Common-all: Common//$(MAKEFILE) FORCE
	cd Common/ && $(MAKE) -f $(MAKEFILE) all
sub-Common-clean: Common//$(MAKEFILE) FORCE
	cd Common/ && $(MAKE) -f $(MAKEFILE) clean
sub-Common-distclean: Common//$(MAKEFILE) FORCE
	cd Common/ && $(MAKE) -f $(MAKEFILE) distclean
sub-Common-install_subtargets: Common//$(MAKEFILE) FORCE
	cd Common/ && $(MAKE) -f $(MAKEFILE) install
sub-Common-uninstall_subtargets: Common//$(MAKEFILE) FORCE
	cd Common/ && $(MAKE) -f $(MAKEFILE) uninstall
Atem//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Atem/ || $(MKDIR) Atem/ 
	cd Atem/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Atem/Atem.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Atem-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Atem/ || $(MKDIR) Atem/ 
	cd Atem/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Atem/Atem.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Atem: Atem//$(MAKEFILE) FORCE
	cd Atem/ && $(MAKE) -f $(MAKEFILE)
sub-Atem-make_default: Atem//$(MAKEFILE) FORCE
	cd Atem/ && $(MAKE) -f $(MAKEFILE) 
sub-Atem-make_first: Atem//$(MAKEFILE) FORCE
	cd Atem/ && $(MAKE) -f $(MAKEFILE) first
sub-Atem-all: Atem//$(MAKEFILE) FORCE
	cd Atem/ && $(MAKE) -f $(MAKEFILE) all
sub-Atem-clean: Atem//$(MAKEFILE) FORCE
	cd Atem/ && $(MAKE) -f $(MAKEFILE) clean
sub-Atem-distclean: Atem//$(MAKEFILE) FORCE
	cd Atem/ && $(MAKE) -f $(MAKEFILE) distclean
sub-Atem-install_subtargets: Atem//$(MAKEFILE) FORCE
	cd Atem/ && $(MAKE) -f $(MAKEFILE) install
sub-Atem-uninstall_subtargets: Atem//$(MAKEFILE) FORCE
	cd Atem/ && $(MAKE) -f $(MAKEFILE) uninstall
Caspar//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Caspar/ || $(MKDIR) Caspar/ 
	cd Caspar/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Caspar/Caspar.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Caspar-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Caspar/ || $(MKDIR) Caspar/ 
	cd Caspar/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Caspar/Caspar.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Caspar: Caspar//$(MAKEFILE) FORCE
	cd Caspar/ && $(MAKE) -f $(MAKEFILE)
sub-Caspar-make_default: Caspar//$(MAKEFILE) FORCE
	cd Caspar/ && $(MAKE) -f $(MAKEFILE) 
sub-Caspar-make_first: Caspar//$(MAKEFILE) FORCE
	cd Caspar/ && $(MAKE) -f $(MAKEFILE) first
sub-Caspar-all: Caspar//$(MAKEFILE) FORCE
	cd Caspar/ && $(MAKE) -f $(MAKEFILE) all
sub-Caspar-clean: Caspar//$(MAKEFILE) FORCE
	cd Caspar/ && $(MAKE) -f $(MAKEFILE) clean
sub-Caspar-distclean: Caspar//$(MAKEFILE) FORCE
	cd Caspar/ && $(MAKE) -f $(MAKEFILE) distclean
sub-Caspar-install_subtargets: Caspar//$(MAKEFILE) FORCE
	cd Caspar/ && $(MAKE) -f $(MAKEFILE) install
sub-Caspar-uninstall_subtargets: Caspar//$(MAKEFILE) FORCE
	cd Caspar/ && $(MAKE) -f $(MAKEFILE) uninstall
TriCaster//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) TriCaster/ || $(MKDIR) TriCaster/ 
	cd TriCaster/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/TriCaster/TriCaster.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-TriCaster-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) TriCaster/ || $(MKDIR) TriCaster/ 
	cd TriCaster/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/TriCaster/TriCaster.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-TriCaster: TriCaster//$(MAKEFILE) FORCE
	cd TriCaster/ && $(MAKE) -f $(MAKEFILE)
sub-TriCaster-make_default: TriCaster//$(MAKEFILE) FORCE
	cd TriCaster/ && $(MAKE) -f $(MAKEFILE) 
sub-TriCaster-make_first: TriCaster//$(MAKEFILE) FORCE
	cd TriCaster/ && $(MAKE) -f $(MAKEFILE) first
sub-TriCaster-all: TriCaster//$(MAKEFILE) FORCE
	cd TriCaster/ && $(MAKE) -f $(MAKEFILE) all
sub-TriCaster-clean: TriCaster//$(MAKEFILE) FORCE
	cd TriCaster/ && $(MAKE) -f $(MAKEFILE) clean
sub-TriCaster-distclean: TriCaster//$(MAKEFILE) FORCE
	cd TriCaster/ && $(MAKE) -f $(MAKEFILE) distclean
sub-TriCaster-install_subtargets: TriCaster//$(MAKEFILE) FORCE
	cd TriCaster/ && $(MAKE) -f $(MAKEFILE) install
sub-TriCaster-uninstall_subtargets: TriCaster//$(MAKEFILE) FORCE
	cd TriCaster/ && $(MAKE) -f $(MAKEFILE) uninstall
Panasonic//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Panasonic/ || $(MKDIR) Panasonic/ 
	cd Panasonic/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Panasonic/Panasonic.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Panasonic-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Panasonic/ || $(MKDIR) Panasonic/ 
	cd Panasonic/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Panasonic/Panasonic.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Panasonic: Panasonic//$(MAKEFILE) FORCE
	cd Panasonic/ && $(MAKE) -f $(MAKEFILE)
sub-Panasonic-make_default: Panasonic//$(MAKEFILE) FORCE
	cd Panasonic/ && $(MAKE) -f $(MAKEFILE) 
sub-Panasonic-make_first: Panasonic//$(MAKEFILE) FORCE
	cd Panasonic/ && $(MAKE) -f $(MAKEFILE) first
sub-Panasonic-all: Panasonic//$(MAKEFILE) FORCE
	cd Panasonic/ && $(MAKE) -f $(MAKEFILE) all
sub-Panasonic-clean: Panasonic//$(MAKEFILE) FORCE
	cd Panasonic/ && $(MAKE) -f $(MAKEFILE) clean
sub-Panasonic-distclean: Panasonic//$(MAKEFILE) FORCE
	cd Panasonic/ && $(MAKE) -f $(MAKEFILE) distclean
sub-Panasonic-install_subtargets: Panasonic//$(MAKEFILE) FORCE
	cd Panasonic/ && $(MAKE) -f $(MAKEFILE) install
sub-Panasonic-uninstall_subtargets: Panasonic//$(MAKEFILE) FORCE
	cd Panasonic/ && $(MAKE) -f $(MAKEFILE) uninstall
Web//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Web/ || $(MKDIR) Web/ 
	cd Web/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Web/Web.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Web-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Web/ || $(MKDIR) Web/ 
	cd Web/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Web/Web.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Web: Web//$(MAKEFILE) FORCE
	cd Web/ && $(MAKE) -f $(MAKEFILE)
sub-Web-make_default: Web//$(MAKEFILE) FORCE
	cd Web/ && $(MAKE) -f $(MAKEFILE) 
sub-Web-make_first: Web//$(MAKEFILE) FORCE
	cd Web/ && $(MAKE) -f $(MAKEFILE) first
sub-Web-all: Web//$(MAKEFILE) FORCE
	cd Web/ && $(MAKE) -f $(MAKEFILE) all
sub-Web-clean: Web//$(MAKEFILE) FORCE
	cd Web/ && $(MAKE) -f $(MAKEFILE) clean
sub-Web-distclean: Web//$(MAKEFILE) FORCE
	cd Web/ && $(MAKE) -f $(MAKEFILE) distclean
sub-Web-install_subtargets: Web//$(MAKEFILE) FORCE
	cd Web/ && $(MAKE) -f $(MAKEFILE) install
sub-Web-uninstall_subtargets: Web//$(MAKEFILE) FORCE
	cd Web/ && $(MAKE) -f $(MAKEFILE) uninstall
Gpi//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Gpi/ || $(MKDIR) Gpi/ 
	cd Gpi/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Gpi/Gpi.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Gpi-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Gpi/ || $(MKDIR) Gpi/ 
	cd Gpi/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Gpi/Gpi.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Gpi: Gpi//$(MAKEFILE) FORCE
	cd Gpi/ && $(MAKE) -f $(MAKEFILE)
sub-Gpi-make_default: Gpi//$(MAKEFILE) FORCE
	cd Gpi/ && $(MAKE) -f $(MAKEFILE) 
sub-Gpi-make_first: Gpi//$(MAKEFILE) FORCE
	cd Gpi/ && $(MAKE) -f $(MAKEFILE) first
sub-Gpi-all: Gpi//$(MAKEFILE) FORCE
	cd Gpi/ && $(MAKE) -f $(MAKEFILE) all
sub-Gpi-clean: Gpi//$(MAKEFILE) FORCE
	cd Gpi/ && $(MAKE) -f $(MAKEFILE) clean
sub-Gpi-distclean: Gpi//$(MAKEFILE) FORCE
	cd Gpi/ && $(MAKE) -f $(MAKEFILE) distclean
sub-Gpi-install_subtargets: Gpi//$(MAKEFILE) FORCE
	cd Gpi/ && $(MAKE) -f $(MAKEFILE) install
sub-Gpi-uninstall_subtargets: Gpi//$(MAKEFILE) FORCE
	cd Gpi/ && $(MAKE) -f $(MAKEFILE) uninstall
Osc//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Osc/ || $(MKDIR) Osc/ 
	cd Osc/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Osc/Osc.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Osc-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Osc/ || $(MKDIR) Osc/ 
	cd Osc/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Osc/Osc.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Osc: Osc//$(MAKEFILE) FORCE
	cd Osc/ && $(MAKE) -f $(MAKEFILE)
sub-Osc-make_default: Osc//$(MAKEFILE) FORCE
	cd Osc/ && $(MAKE) -f $(MAKEFILE) 
sub-Osc-make_first: Osc//$(MAKEFILE) FORCE
	cd Osc/ && $(MAKE) -f $(MAKEFILE) first
sub-Osc-all: Osc//$(MAKEFILE) FORCE
	cd Osc/ && $(MAKE) -f $(MAKEFILE) all
sub-Osc-clean: Osc//$(MAKEFILE) FORCE
	cd Osc/ && $(MAKE) -f $(MAKEFILE) clean
sub-Osc-distclean: Osc//$(MAKEFILE) FORCE
	cd Osc/ && $(MAKE) -f $(MAKEFILE) distclean
sub-Osc-install_subtargets: Osc//$(MAKEFILE) FORCE
	cd Osc/ && $(MAKE) -f $(MAKEFILE) install
sub-Osc-uninstall_subtargets: Osc//$(MAKEFILE) FORCE
	cd Osc/ && $(MAKE) -f $(MAKEFILE) uninstall
Repository//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Repository/ || $(MKDIR) Repository/ 
	cd Repository/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Repository/Repository.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Repository-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Repository/ || $(MKDIR) Repository/ 
	cd Repository/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Repository/Repository.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Repository: Repository//$(MAKEFILE) FORCE
	cd Repository/ && $(MAKE) -f $(MAKEFILE)
sub-Repository-make_default: Repository//$(MAKEFILE) FORCE
	cd Repository/ && $(MAKE) -f $(MAKEFILE) 
sub-Repository-make_first: Repository//$(MAKEFILE) FORCE
	cd Repository/ && $(MAKE) -f $(MAKEFILE) first
sub-Repository-all: Repository//$(MAKEFILE) FORCE
	cd Repository/ && $(MAKE) -f $(MAKEFILE) all
sub-Repository-clean: Repository//$(MAKEFILE) FORCE
	cd Repository/ && $(MAKE) -f $(MAKEFILE) clean
sub-Repository-distclean: Repository//$(MAKEFILE) FORCE
	cd Repository/ && $(MAKE) -f $(MAKEFILE) distclean
sub-Repository-install_subtargets: Repository//$(MAKEFILE) FORCE
	cd Repository/ && $(MAKE) -f $(MAKEFILE) install
sub-Repository-uninstall_subtargets: Repository//$(MAKEFILE) FORCE
	cd Repository/ && $(MAKE) -f $(MAKEFILE) uninstall
Core//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Core/ || $(MKDIR) Core/ 
	cd Core/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Core/Core.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Core-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Core/ || $(MKDIR) Core/ 
	cd Core/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Core/Core.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Core: Core//$(MAKEFILE) FORCE
	cd Core/ && $(MAKE) -f $(MAKEFILE)
sub-Core-make_default: Core//$(MAKEFILE) FORCE
	cd Core/ && $(MAKE) -f $(MAKEFILE) 
sub-Core-make_first: Core//$(MAKEFILE) FORCE
	cd Core/ && $(MAKE) -f $(MAKEFILE) first
sub-Core-all: Core//$(MAKEFILE) FORCE
	cd Core/ && $(MAKE) -f $(MAKEFILE) all
sub-Core-clean: Core//$(MAKEFILE) FORCE
	cd Core/ && $(MAKE) -f $(MAKEFILE) clean
sub-Core-distclean: Core//$(MAKEFILE) FORCE
	cd Core/ && $(MAKE) -f $(MAKEFILE) distclean
sub-Core-install_subtargets: Core//$(MAKEFILE) FORCE
	cd Core/ && $(MAKE) -f $(MAKEFILE) install
sub-Core-uninstall_subtargets: Core//$(MAKEFILE) FORCE
	cd Core/ && $(MAKE) -f $(MAKEFILE) uninstall
Widgets//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Widgets/ || $(MKDIR) Widgets/ 
	cd Widgets/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Widgets/Widgets.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Widgets-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Widgets/ || $(MKDIR) Widgets/ 
	cd Widgets/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Widgets/Widgets.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Widgets: Widgets//$(MAKEFILE) FORCE
	cd Widgets/ && $(MAKE) -f $(MAKEFILE)
sub-Widgets-make_default: Widgets//$(MAKEFILE) FORCE
	cd Widgets/ && $(MAKE) -f $(MAKEFILE) 
sub-Widgets-make_first: Widgets//$(MAKEFILE) FORCE
	cd Widgets/ && $(MAKE) -f $(MAKEFILE) first
sub-Widgets-all: Widgets//$(MAKEFILE) FORCE
	cd Widgets/ && $(MAKE) -f $(MAKEFILE) all
sub-Widgets-clean: Widgets//$(MAKEFILE) FORCE
	cd Widgets/ && $(MAKE) -f $(MAKEFILE) clean
sub-Widgets-distclean: Widgets//$(MAKEFILE) FORCE
	cd Widgets/ && $(MAKE) -f $(MAKEFILE) distclean
sub-Widgets-install_subtargets: Widgets//$(MAKEFILE) FORCE
	cd Widgets/ && $(MAKE) -f $(MAKEFILE) install
sub-Widgets-uninstall_subtargets: Widgets//$(MAKEFILE) FORCE
	cd Widgets/ && $(MAKE) -f $(MAKEFILE) uninstall
Shell//$(MAKEFILE): 
	@$(CHK_DIR_EXISTS) Shell/ || $(MKDIR) Shell/ 
	cd Shell/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Shell/Shell.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Shell-qmake_all:  FORCE
	@$(CHK_DIR_EXISTS) Shell/ || $(MKDIR) Shell/ 
	cd Shell/ && $(QMAKE) /home/sysnova/Documents/Client-master/src/Shell/Shell.pro -spec /usr/share/qt4/mkspecs/linux-g++ -o $(MAKEFILE)
sub-Shell: Shell//$(MAKEFILE) FORCE
	cd Shell/ && $(MAKE) -f $(MAKEFILE)
sub-Shell-make_default: Shell//$(MAKEFILE) FORCE
	cd Shell/ && $(MAKE) -f $(MAKEFILE) 
sub-Shell-make_first: Shell//$(MAKEFILE) FORCE
	cd Shell/ && $(MAKE) -f $(MAKEFILE) first
sub-Shell-all: Shell//$(MAKEFILE) FORCE
	cd Shell/ && $(MAKE) -f $(MAKEFILE) all
sub-Shell-clean: Shell//$(MAKEFILE) FORCE
	cd Shell/ && $(MAKE) -f $(MAKEFILE) clean
sub-Shell-distclean: Shell//$(MAKEFILE) FORCE
	cd Shell/ && $(MAKE) -f $(MAKEFILE) distclean
sub-Shell-install_subtargets: Shell//$(MAKEFILE) FORCE
	cd Shell/ && $(MAKE) -f $(MAKEFILE) install
sub-Shell-uninstall_subtargets: Shell//$(MAKEFILE) FORCE
	cd Shell/ && $(MAKE) -f $(MAKEFILE) uninstall

Makefile: Solution.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Solution.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
qmake: qmake_all FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile Solution.pro

qmake_all: sub-Common-qmake_all sub-Atem-qmake_all sub-Caspar-qmake_all sub-TriCaster-qmake_all sub-Panasonic-qmake_all sub-Web-qmake_all sub-Gpi-qmake_all sub-Osc-qmake_all sub-Repository-qmake_all sub-Core-qmake_all sub-Widgets-qmake_all sub-Shell-qmake_all FORCE

make_default: sub-Common-make_default sub-Atem-make_default sub-Caspar-make_default sub-TriCaster-make_default sub-Panasonic-make_default sub-Web-make_default sub-Gpi-make_default sub-Osc-make_default sub-Repository-make_default sub-Core-make_default sub-Widgets-make_default sub-Shell-make_default FORCE
make_first: sub-Common-make_first sub-Atem-make_first sub-Caspar-make_first sub-TriCaster-make_first sub-Panasonic-make_first sub-Web-make_first sub-Gpi-make_first sub-Osc-make_first sub-Repository-make_first sub-Core-make_first sub-Widgets-make_first sub-Shell-make_first FORCE
all: sub-Common-all sub-Atem-all sub-Caspar-all sub-TriCaster-all sub-Panasonic-all sub-Web-all sub-Gpi-all sub-Osc-all sub-Repository-all sub-Core-all sub-Widgets-all sub-Shell-all FORCE
clean: sub-Common-clean sub-Atem-clean sub-Caspar-clean sub-TriCaster-clean sub-Panasonic-clean sub-Web-clean sub-Gpi-clean sub-Osc-clean sub-Repository-clean sub-Core-clean sub-Widgets-clean sub-Shell-clean FORCE
distclean: sub-Common-distclean sub-Atem-distclean sub-Caspar-distclean sub-TriCaster-distclean sub-Panasonic-distclean sub-Web-distclean sub-Gpi-distclean sub-Osc-distclean sub-Repository-distclean sub-Core-distclean sub-Widgets-distclean sub-Shell-distclean FORCE
	-$(DEL_FILE) Makefile
install_subtargets: sub-Common-install_subtargets sub-Atem-install_subtargets sub-Caspar-install_subtargets sub-TriCaster-install_subtargets sub-Panasonic-install_subtargets sub-Web-install_subtargets sub-Gpi-install_subtargets sub-Osc-install_subtargets sub-Repository-install_subtargets sub-Core-install_subtargets sub-Widgets-install_subtargets sub-Shell-install_subtargets FORCE
uninstall_subtargets: sub-Common-uninstall_subtargets sub-Atem-uninstall_subtargets sub-Caspar-uninstall_subtargets sub-TriCaster-uninstall_subtargets sub-Panasonic-uninstall_subtargets sub-Web-uninstall_subtargets sub-Gpi-uninstall_subtargets sub-Osc-uninstall_subtargets sub-Repository-uninstall_subtargets sub-Core-uninstall_subtargets sub-Widgets-uninstall_subtargets sub-Shell-uninstall_subtargets FORCE

sub-Common-check: Common/$(MAKEFILE)
	cd Common/ && $(MAKE) -f $(MAKEFILE) check
sub-Atem-check: Atem/$(MAKEFILE)
	cd Atem/ && $(MAKE) -f $(MAKEFILE) check
sub-Caspar-check: Caspar/$(MAKEFILE)
	cd Caspar/ && $(MAKE) -f $(MAKEFILE) check
sub-TriCaster-check: TriCaster/$(MAKEFILE)
	cd TriCaster/ && $(MAKE) -f $(MAKEFILE) check
sub-Panasonic-check: Panasonic/$(MAKEFILE)
	cd Panasonic/ && $(MAKE) -f $(MAKEFILE) check
sub-Web-check: Web/$(MAKEFILE)
	cd Web/ && $(MAKE) -f $(MAKEFILE) check
sub-Gpi-check: Gpi/$(MAKEFILE)
	cd Gpi/ && $(MAKE) -f $(MAKEFILE) check
sub-Osc-check: Osc/$(MAKEFILE)
	cd Osc/ && $(MAKE) -f $(MAKEFILE) check
sub-Repository-check: Repository/$(MAKEFILE)
	cd Repository/ && $(MAKE) -f $(MAKEFILE) check
sub-Core-check: Core/$(MAKEFILE)
	cd Core/ && $(MAKE) -f $(MAKEFILE) check
sub-Widgets-check: Widgets/$(MAKEFILE)
	cd Widgets/ && $(MAKE) -f $(MAKEFILE) check
sub-Shell-check: Shell/$(MAKEFILE)
	cd Shell/ && $(MAKE) -f $(MAKEFILE) check
check: sub-Common-check sub-Atem-check sub-Caspar-check sub-TriCaster-check sub-Panasonic-check sub-Web-check sub-Gpi-check sub-Osc-check sub-Repository-check sub-Core-check sub-Widgets-check sub-Shell-check

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all
install: install_subtargets  FORCE

uninstall:  uninstall_subtargets FORCE

FORCE:

